id: I85855235
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-18T05:40:48+00:00'
last_modified: '2022-06-10T05:16:36.427568+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD107937
  title: གསུང་འབུམ། ངག་དབང་བློ་བཟང་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '5857':
      image_group_id: I1PD107939
      title: Volume 1 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 632
      order: 1
      base_file: 5857.txt
    283C:
      image_group_id: I1PD107940
      title: Volume 2 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 574
      order: 2
      base_file: 283C.txt
    0B50:
      image_group_id: I1PD107941
      title: Volume 3 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 566
      order: 3
      base_file: 0B50.txt
    A8F6:
      image_group_id: I1PD107942
      title: Volume 4 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 578
      order: 4
      base_file: A8F6.txt
    A363:
      image_group_id: I1PD107943
      title: Volume 5 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 566
      order: 5
      base_file: A363.txt
    B220:
      image_group_id: I1PD107944
      title: Volume 6 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 420
      order: 6
      base_file: B220.txt
    '1501':
      image_group_id: I1PD107945
      title: Volume 7 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 370
      order: 7
      base_file: 1501.txt
    47E9:
      image_group_id: I1PD107946
      title: Volume 8 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 590
      order: 8
      base_file: 47E9.txt
    FB62:
      image_group_id: I1PD107947
      title: Volume 9 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 478
      order: 9
      base_file: FB62.txt
    9D48:
      image_group_id: I1PD107948
      title: Volume 10 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 548
      order: 10
      base_file: 9D48.txt
    '8248':
      image_group_id: I1PD107949
      title: Volume 11 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 596
      order: 11
      base_file: 8248.txt
    7E7D:
      image_group_id: I1PD107950
      title: Volume 12 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 620
      order: 12
      base_file: 7E7D.txt
    '1558':
      image_group_id: I1PD107951
      title: Volume 13 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 542
      order: 13
      base_file: 1558.txt
    F17D:
      image_group_id: I1PD107952
      title: Volume 14 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 538
      order: 14
      base_file: F17D.txt
    A5A2:
      image_group_id: I1PD107953
      title: Volume 15 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 628
      order: 15
      base_file: A5A2.txt
    16DF:
      image_group_id: I1PD107954
      title: Volume 16 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 578
      order: 16
      base_file: 16DF.txt
    010D:
      image_group_id: I1PD107955
      title: Volume 17 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 694
      order: 17
      base_file: 010D.txt
    99EA:
      image_group_id: I1PD107956
      title: Volume 18 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 500
      order: 18
      base_file: 99EA.txt
    DCA4:
      image_group_id: I1PD107957
      title: Volume 19 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 404
      order: 19
      base_file: DCA4.txt
    FB5A:
      image_group_id: I1PD107958
      title: Volume 20 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 414
      order: 20
      base_file: FB5A.txt
    2C8B:
      image_group_id: I1PD107959
      title: Volume 21 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 486
      order: 21
      base_file: 2C8B.txt
    BB88:
      image_group_id: I1PD107960
      title: Volume 22 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 638
      order: 22
      base_file: BB88.txt
    0D94:
      image_group_id: I1PD107961
      title: Volume 23 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 514
      order: 23
      base_file: 0D94.txt
    EA42:
      image_group_id: I1PD107962
      title: Volume 24 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 598
      order: 24
      base_file: EA42.txt
    '4275':
      image_group_id: I1PD107963
      title: Volume 25 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 630
      order: 25
      base_file: 4275.txt
    988B:
      image_group_id: I1PD107964
      title: Volume 26 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 634
      order: 26
      base_file: 988B.txt
    45FA:
      image_group_id: I1PD107965
      title: Volume 27 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 630
      order: 27
      base_file: 45FA.txt
    1A5C:
      image_group_id: I1PD107966
      title: Volume 28 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 524
      order: 28
      base_file: 1A5C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
